# Generated by Django 4.0.4 on 2022-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(blank=True, max_length=225, null=True, upload_to=''),
        ),
    ]
